### PR TITLE
Feat/makefile and tests

### LINKED ISSUE #6: suggestion: Add make file and go tests
Hello! I really like your project and was wondering if you'd be open for a PR with some go tests and a make file to streamline development / building , let me know if thats something you'd like to see!

### PR DESCRIPTION
**Pull request by kek-Sec**
This pull request introduces several key changes, including the addition of a `Makefile` for build automation, updates to the `go.mod` dependencies, and the addition of various unit tests to improve code coverage and reliability. Below is a summary of the most important changes:

### Build Automation:
* Added a `Makefile` to streamline the build, test, and run processes for the project. This includes targets for building, cleaning, formatting, running tests, and installing dependencies.

### Dependency Management:
* Updated the `go.mod` file to include several new indirect dependencies such as `github.com/davecgh/go-spew`, `github.com/pmezard/go-difflib`, `github.com/stretchr/testify`, and `gopkg.in/yaml.v3`.

### Unit Tests:
* Added unit tests for key mappings in `helpers/keymaps_test.go` to verify the initialization and functionality of common and suggestion input key bindings.
* Added unit tests for the `HubModel` in `hub/hub_test.go` to test initialization, update functions, search functionality, and repository addition.
* Added unit tests for the `InstallModel` in `releases/install_test.go` to verify initialization, key handling, and message handling for the installation process.
* Added unit tests for the `AddModel` in `repositories/add_test.go` to verify initialization, key handling, and input clearing functionality.

These changes collectively enhance the project's build process, dependency management, and test coverage.

### CODE REVIEW

**Comment by george-petrakis** [comment]
@pidanou  Let me know if you like the style , adding some CI would be great.

**Comment by pidanou** [comment]
> @pidanou Let me know if you like the style , adding some CI would be great.

Hey! Thank you so much for the PR.
Now that I look at your tests, I am wondering if we should or not  focus textinputs (or any model) on init.

How I see it:
- Option 1 : All the models should have an input focused at init. All the state is managed on that model and we never focus from a parent. We just need to make sure there is no way a keypress is sent by accident to the child as something is always focused; and that after pressing `esc` or "leaving" the model, we manage the focus accordingly.
- Option 2: We don't focus on init and we focus a child model  input (or any other model) only on parent keypress. This means, there will be no way that a keypress is sent to the child model by accident. But we manage the state in 2 different places.

Option 1 looks prettier as we never care about the child models.

Tell me what you think!
If you also think option 1 is the best, I think there are other places where I didn't focus on init.

Apart from that question, the PR is great and I'll be happy to merge it.

**Comment by george-petrakis** [comment]
> > @pidanou Let me know if you like the style , adding some CI would be great.
> 
> Hey! Thank you so much for the PR. Now that I look at your tests, I am wondering if we should or not focus textinputs (or any model) on init.
> 
> How I see it:
> 
> * Option 1 : All the models should have an input focused at init. All the state is managed on that model and we never focus from a parent. We just need to make sure there is no way a keypress is sent by accident to the child as something is always focused; and that after pressing `esc` or "leaving" the model, we manage the focus accordingly.
> * Option 2: We don't focus on init and we focus a child model  input (or any other model) only on parent keypress. This means, there will be no way that a keypress is sent to the child model by accident. But we manage the state in 2 different places.
> 
> Option 1 looks prettier as we never care about the child models.
> 
> Tell me what you think! If you also think option 1 is the best, I think there are other places where I didn't focus on init.
> 
> Apart from that question, the PR is great and I'll be happy to merge it.



Thank you for the thoughtful feedback! After considering both options, I agree that Option 1 is the better approach. Having each model manage its own focus state keeps things encapsulated and makes the code easier to maintain and scale. 

 Let me know if there's anything you'd like me to adjust.

**Comment by pidanou** [comment]
> > > @pidanou Let me know if you like the style , adding some CI would be great.
> > 
> > 
> > Hey! Thank you so much for the PR. Now that I look at your tests, I am wondering if we should or not focus textinputs (or any model) on init.
> > How I see it:
> > 
> > * Option 1 : All the models should have an input focused at init. All the state is managed on that model and we never focus from a parent. We just need to make sure there is no way a keypress is sent by accident to the child as something is always focused; and that after pressing `esc` or "leaving" the model, we manage the focus accordingly.
> > * Option 2: We don't focus on init and we focus a child model  input (or any other model) only on parent keypress. This means, there will be no way that a keypress is sent to the child model by accident. But we manage the state in 2 different places.
> > 
> > Option 1 looks prettier as we never care about the child models.
> > Tell me what you think! If you also think option 1 is the best, I think there are other places where I didn't focus on init.
> > Apart from that question, the PR is great and I'll be happy to merge it.
> 
> Thank you for the thoughtful feedback! After considering both options, I agree that Option 1 is the better approach. Having each model manage its own focus state keeps things encapsulated and makes the code easier to maintain and scale.
> 
> Let me know if there's anything you'd like me to adjust.

I will merge you PR for now as I believe changing the message flow is out of the scope of this PR. I will open an issue about changing the state management. Thanks a lot!

**Pull request merged**
